// src/components/Portfolio/Portfolio.tsx
import React, { useState } from 'react';
import { Code2, Github, Lock, X } from 'lucide-react';
import { projectsData } from '../../data/projectsData';

export const Portfolio = () => {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);

  return (
    <section id="portfolio" className="py-20 px-8 bg-white">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold mb-12 text-center text-gray-800 flex items-center justify-center">
          <Code2 className="w-8 h-8 mr-3 text-red-600 icon-spin" />
          Projets
        </h2>
        <div className="grid md:grid-cols-2 gap-8">
          {projectsData.map((project) => (
            <div 
              key={project.name}
              className="project-card bg-white p-6 rounded-lg shadow-lg hover:shadow-xl transition-all duration-300"
            >
              <h3 className="font-bold text-xl mb-4 flex items-center text-gray-800">
                {project.link === '#' ? (
                  <Lock className="w-5 h-5 mr-2 text-red-600" />
                ) : (
                  <Github className="w-5 h-5 mr-2 text-red-600" />
                )}
                {project.name}
              </h3>
              <div className="mb-4">
                {project.media.type === 'video' ? (
                  <video 
                    className="w-full h-48 object-cover rounded-lg mb-4 border border-gray-200"
                    controls
                    preload="metadata"
                  >
                    <source src={project.media.src} type="video/mp4" />
                    Votre navigateur ne supporte pas la lecture de vidéos.
                  </video>
                ) : (
                  <div className="relative">
                    <img 
                      src={project.media.src}
                      alt={project.media.alt}
                      className={`w-full h-48 rounded-lg mb-4 border border-gray-200 ${
                        ['Popeye', 'Portfolio', 'CultureQuiz'].includes(project.name)
                          ? 'object-cover'
                          : 'object-contain'
                      } ${
                        project.name.includes('NSA') ? 'cursor-zoom-in hover:opacity-90' : ''
                      }`}
                      onClick={() => {
                        if (project.name.includes('NSA')) {
                          setSelectedImage(project.media.src);
                        }
                      }}
                    />
                  </div>
                )}
                {project.name === 'NSA (Network Security Administration)' && (
                  <p className="text-sm text-gray-500 text-center italic">
                    Cliquez sur l'image pour l'agrandir
                  </p>
                )}
              </div>
              <p className="text-gray-600">
                {project.description}
              </p>
              {project.link !== '#' && (
                <a 
                  href={project.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center mt-4 text-red-600 hover:text-red-700"
                >
                  <Github className="w-4 h-4 mr-2" />
                  Voir sur GitHub
                </a>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Modal pour l'image agrandie */}
      {selectedImage && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-75 z-50 flex items-center justify-center p-4"
          onClick={() => setSelectedImage(null)}
        >
          <button 
            className="absolute top-4 right-4 text-white hover:text-red-400 transition-colors"
            onClick={() => setSelectedImage(null)}
            title="Fermer la vue agrandie"
            aria-label="Fermer la vue agrandie"
          >
            <X className="w-8 h-8" />
          </button>
          <img 
            src={selectedImage} 
            alt="Vue agrandie"
            className="max-w-full max-h-[90vh] object-contain rounded-lg"
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}
    </section>
  );
};

// components/Portfolio.vue
<template>
  <section id="portfolio" class="py-32 px-8 bg-white dark:bg-gray-900">
    <div class="max-w-6xl mx-auto">
      <h2 class="text-3xl font-bold mb-12 text-center text-gray-800 dark:text-gray-100">
        {{ t.portfolio.title }}
      </h2>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div
          v-for="project in projects"
          :key="project.name"
          class="project-card bg-white dark:bg-gray-800 rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 overflow-hidden border border-gray-200 dark:border-gray-700 group"
        >
          <div class="relative overflow-hidden">
            <video
              v-if="project.media.type === 'video'"
              class="w-full h-48 object-cover"
              controls
              preload="metadata"
            >
              <source :src="project.media.src" type="video/mp4" />
              {{ t.portfolio.videoNotSupported }}
            </video>
            <img
              v-else
              :src="project.media.src"
              :alt="project.media.alt"
              :class="[
                'w-full h-48 object-cover transition-transform duration-300 group-hover:scale-110',
                project.name.includes('NSA') ? 'cursor-zoom-in' : ''
              ]"
              @click="project.name.includes('NSA') && openImageModal(project.media.src)"
            />
            <div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          </div>
          
          <div class="p-6">
            <h3 class="font-bold text-xl mb-3 flex items-center text-gray-800 dark:text-gray-100">
              <span v-if="project.link === '#'" class="mr-2">🔒</span>
              <span v-else class="mr-2">⚙️</span>
              {{ project.name }}
            </h3>
            
            <p class="text-gray-600 dark:text-gray-300 text-sm mb-4">{{ project.description }}</p>
            
            <a
              v-if="project.link && !project.name.includes('NSA')"
              :href="project.link"
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center text-primary-blue dark:text-accent-blue hover:text-secondary-blue dark:hover:text-blue-300 transition-colors font-medium"
            >
              <span class="mr-2">→</span>
              {{ t.portfolio.viewGithub }}
            </a>
            <div v-else-if="project.name.includes('NSA')" class="inline-flex items-center text-gray-400 dark:text-gray-500 cursor-not-allowed select-none">
              <span class="mr-2">🔒</span>
              {{ t.portfolio.viewGithub }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal pour l'image agrandie -->
    <Transition name="modal">
      <div
        v-if="selectedImage"
        class="fixed inset-0 bg-black bg-opacity-90 z-50 flex items-center justify-center p-4"
        @click="selectedImage = null"
      >
        <button
          class="absolute top-4 right-4 text-white hover:text-blue-400 transition-colors text-4xl"
          @click="selectedImage = null"
          :title="t.portfolio.close"
          :aria-label="t.portfolio.close"
        >
          ✕
        </button>
        <img
          :src="selectedImage"
          :alt="t.portfolio.enlargedView"
          class="max-w-full max-h-[90vh] object-contain rounded-lg"
          @click.stop
        />
      </div>
    </Transition>
  </section>
</template>

<script setup>
const { currentLanguage } = useLanguage()
const { t } = useTranslations()
const selectedImage = ref(null)

const openImageModal = (src) => {
  selectedImage.value = src
}

const projects = computed(() => [
  {
    name: 'Popeye',
    link: 'https://github.com/Deniz09OK/Popeye',
    description: t.value.portfolio.popeyeDesc,
    media: {
      type: 'image',
      src: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      alt: 'Docker containers illustration'
    }
  },
  {
    name: 'Portfolio',
    link: 'https://github.com/Deniz09OK/Portfolio-deniz',
    description: t.value.portfolio.portfolioDesc,
    media: {
      type: 'image',
      src: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      alt: 'Code on a computer screen'
    }
  },
  {
    name: 'NSA (Network Security Administration)',
    link: '#',
    description: t.value.portfolio.nsaDesc,
    media: {
      type: 'image',
      src: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      alt: 'Network security illustration'
    }
  },
  {
    name: 'CultureQuiz',
    link: 'https://github.com/Deniz09OK/CultureQuiz',
    description: t.value.portfolio.cultureQuizDesc,
    media: {
      type: 'image',
      src: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80',
      alt: 'Quiz and learning'
    }
  },
  {
    name: 'AI-Morpion',
    link: 'https://github.com/Deniz09OK/AI-Morpion',
    description: t.value.portfolio.aiMorpionDesc,
    media: {
      type: 'image',
      src: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      alt: 'Tic-tac-toe game'
    }
  },
  {
    name: 'EpiQuest',
    link: 'https://github.com/Deniz09OK/Projet-Jeu-Java',
    description: t.value.portfolio.epiQuestDesc,
    media: {
      type: 'image',
      src: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      alt: 'Retro video game'
    }
  }
])
</script>
