// components/Languages.vue
<template>
  <section id="languages" class="py-32 px-8 bg-white dark:bg-gray-800 relative overflow-hidden">
    <!-- Formes décoratives animées -->
    <div class="absolute top-20 right-10 w-72 h-72 bg-blue-300 dark:bg-blue-500 rounded-full mix-blend-multiply dark:mix-blend-screen filter blur-xl opacity-30 dark:opacity-20 animate-float"></div>
    <div class="absolute bottom-20 left-10 w-80 h-80 bg-indigo-300 dark:bg-indigo-500 rounded-full mix-blend-multiply dark:mix-blend-screen filter blur-xl opacity-30 dark:opacity-20 animate-float delay-200"></div>
    
    <div class="max-w-4xl mx-auto relative z-10">
      <h2 class="text-3xl font-bold mb-12 text-center text-gray-800 dark:text-gray-100 animate-fade-in-down">
        {{ t.languages.title }}
      </h2>
      <div class="grid md:grid-cols-3 gap-6">
        <div
          v-for="(lang, index) in languages"
          :key="lang.name"
          class="language-card bg-gradient-to-br from-blue-50 to-blue-100 dark:from-blue-900/40 dark:to-indigo-900/40 p-8 rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 border-2 border-blue-200 dark:border-blue-500/50 hover:scale-110 hover:-translate-y-2 animate-fade-in-up backdrop-blur-sm"
          :style="{ animationDelay: `${index * 0.1}s` }"
        >
          <div class="text-center">
            <span class="text-5xl mb-4 block drop-shadow-lg">{{ lang.flag }}</span>
            <h3 class="text-xl font-bold text-gray-800 dark:text-white mb-3 drop-shadow-sm">
              {{ lang.name }}
            </h3>
            <div class="px-4 py-2 bg-white/50 dark:bg-blue-600/30 rounded-full backdrop-blur-sm border border-blue-300 dark:border-blue-400/50">
              <p class="text-gray-700 dark:text-blue-100 font-semibold">{{ lang.level }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
const { currentLanguage } = useLanguage()
const { t } = useTranslations()

const languages = computed(() => [
  {
    name: t.value.languages.french,
    level: t.value.languages.native,
    flag: '🇫🇷'
  },
  {
    name: t.value.languages.turkish,
    level: t.value.languages.native,
    flag: '🇹🇷'
  },
  {
    name: t.value.languages.english,
    level: t.value.languages.toeic,
    flag: '🇬🇧'
  }
])
</script>

// src/components/Languages/Languages.tsx
import { Languages as LanguagesIcon, Globe } from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';
import { translations } from '../../translations/translations';

export const Languages = () => {
  const { language } = useLanguage();
  const t = translations[language];

  return (
    <section id="languages" className="py-20 px-8 bg-gray-50">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold mb-12 text-center text-gray-800 flex items-center justify-center">
          <LanguagesIcon className="w-8 h-8 mr-3 text-red-600 icon-spin" />
          {t.languages}
        </h2>
        <div className="grid md:grid-cols-3 gap-6">
          {[
            { name: language === 'fr' ? 'Français' : 'French', level: language === 'fr' ? 'Langue maternelle' : 'Native language' },
            { name: language === 'fr' ? 'Turc' : 'Turkish', level: language === 'fr' ? 'Langue maternelle' : 'Native language' },
            { name: language === 'fr' ? 'Anglais' : 'English', level: 'TOEIC 790/990' }
          ].map((lang, index) => (
            <div 
              key={lang.name}
              className="language-card bg-white p-6 rounded-lg shadow-lg hover:shadow-xl transition-all duration-300"
              style={{ animationDelay: `${index * 0.2}s` }}
            >
              <h3 className="text-xl font-bold text-gray-800 mb-2 flex items-center">
                <Globe className="w-5 h-5 mr-2 text-red-600" />
                {lang.name}
              </h3>
              <p className="text-gray-600">{lang.level}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
